-- Synchronize the database-controlled vocabulary with promoted ontology v0.1.1.
-- This is idempotent: existing tags are updated, missing tags are inserted, and
-- ontology tags that had been retired are reactivated.

insert into public.tags (slug, display_name, category)
values
  ('romantic-comedy', 'Romantic Comedy', 'subgenre'),
  ('dark-comedy', 'Dark Comedy', 'subgenre'),
  ('black-comedy', 'Black Comedy', 'subgenre'),
  ('screwball-comedy', 'Screwball Comedy', 'subgenre'),
  ('satire', 'Satire', 'subgenre'),
  ('parody-spoof', 'Parody / Spoof', 'subgenre'),
  ('workplace-comedy', 'Workplace Comedy', 'subgenre'),
  ('coming-of-age-comedy', 'Coming-of-Age Comedy', 'subgenre'),
  ('buddy-comedy', 'Buddy Comedy', 'subgenre'),
  ('breakup-comedy', 'Breakup Comedy', 'subgenre'),
  ('sex-comedy', 'Sex Comedy', 'subgenre'),
  ('stoner-comedy', 'Stoner Comedy', 'subgenre'),
  ('absurdist-comedy', 'Absurdist Comedy', 'subgenre'),
  ('mockumentary', 'Mockumentary', 'subgenre'),
  ('family-drama', 'Family Drama', 'subgenre'),
  ('relationship-drama', 'Relationship Drama', 'subgenre'),
  ('psychological-drama', 'Psychological Drama', 'subgenre'),
  ('legal-drama', 'Legal Drama', 'subgenre'),
  ('political-drama', 'Political Drama', 'subgenre'),
  ('historical-drama', 'Historical Drama', 'subgenre'),
  ('social-drama', 'Social Drama', 'subgenre'),
  ('workplace-drama', 'Workplace Drama', 'subgenre'),
  ('coming-of-age-drama', 'Coming-of-Age Drama', 'subgenre'),
  ('sports-drama', 'Sports Drama', 'subgenre'),
  ('showbiz-drama', 'Showbiz Drama', 'subgenre'),
  ('crime-drama', 'Crime Drama', 'subgenre'),
  ('gangster', 'Gangster', 'subgenre'),
  ('heist', 'Heist', 'subgenre'),
  ('detective', 'Detective', 'subgenre'),
  ('police-procedural', 'Police Procedural', 'subgenre'),
  ('neo-noir', 'Neo-Noir', 'subgenre'),
  ('courtroom-crime', 'Courtroom Crime', 'subgenre'),
  ('organized-crime', 'Organized Crime', 'subgenre'),
  ('psychological-thriller', 'Psychological Thriller', 'subgenre'),
  ('crime-thriller', 'Crime Thriller', 'subgenre'),
  ('political-thriller', 'Political Thriller', 'subgenre'),
  ('conspiracy-thriller', 'Conspiracy Thriller', 'subgenre'),
  ('espionage-thriller', 'Espionage Thriller', 'subgenre'),
  ('erotic-thriller', 'Erotic Thriller', 'subgenre'),
  ('tech-thriller', 'Tech Thriller', 'subgenre'),
  ('survival-thriller', 'Survival Thriller', 'subgenre'),
  ('revenge-thriller', 'Revenge Thriller', 'subgenre'),
  ('action-thriller', 'Action-Thriller', 'subgenre'),
  ('martial-arts', 'Martial Arts', 'subgenre'),
  ('adventure-action', 'Adventure Action', 'subgenre'),
  ('military-action', 'Military Action', 'subgenre'),
  ('superhero', 'Superhero', 'subgenre'),
  ('revenge-action', 'Revenge Action', 'subgenre'),
  ('disaster', 'Disaster', 'subgenre'),
  ('psychological-horror', 'Psychological Horror', 'subgenre'),
  ('supernatural-horror', 'Supernatural Horror', 'subgenre'),
  ('folk-horror', 'Folk Horror', 'subgenre'),
  ('body-horror', 'Body Horror', 'subgenre'),
  ('slasher', 'Slasher', 'subgenre'),
  ('creature-feature', 'Creature Feature', 'subgenre'),
  ('gothic-horror', 'Gothic Horror', 'subgenre'),
  ('cosmic-horror', 'Cosmic Horror', 'subgenre'),
  ('horror-comedy', 'Horror-Comedy', 'subgenre'),
  ('survival-horror', 'Survival Horror', 'subgenre'),
  ('sci-fi-horror', 'Sci-Fi Horror', 'subgenre'),
  ('hard-sci-fi', 'Hard Sci-Fi', 'subgenre'),
  ('dystopian-sci-fi', 'Dystopian Sci-Fi', 'subgenre'),
  ('cyberpunk', 'Cyberpunk', 'subgenre'),
  ('space-opera', 'Space Opera', 'subgenre'),
  ('alien-first-contact', 'Alien First Contact', 'subgenre'),
  ('time-travel', 'Time Travel', 'subgenre'),
  ('tech-sci-fi', 'Tech Sci-Fi', 'subgenre'),
  ('post-apocalyptic', 'Post-Apocalyptic', 'subgenre'),
  ('epic-fantasy', 'Epic Fantasy', 'subgenre'),
  ('dark-fantasy', 'Dark Fantasy', 'subgenre'),
  ('urban-fantasy', 'Urban Fantasy', 'subgenre'),
  ('magical-realism', 'Magical Realism', 'subgenre'),
  ('fairy-tale-fable', 'Fairy Tale / Fable', 'subgenre'),
  ('sword-and-sorcery', 'Sword and Sorcery', 'subgenre'),
  ('romantic-drama', 'Romantic Drama', 'subgenre'),
  ('period-romance', 'Period Romance', 'subgenre'),
  ('tragic-romance', 'Tragic Romance', 'subgenre'),
  ('erotic-romance', 'Erotic Romance', 'subgenre'),
  ('murder-mystery', 'Murder Mystery', 'subgenre'),
  ('whodunit', 'Whodunit', 'subgenre'),
  ('mystery-thriller', 'Mystery-Thriller', 'subgenre'),
  ('puzzle-mystery', 'Puzzle Mystery', 'subgenre'),
  ('combat-film', 'Combat Film', 'subgenre'),
  ('anti-war-film', 'Anti-War Film', 'subgenre'),
  ('pow-escape', 'POW / Escape', 'subgenre'),
  ('home-front-war-drama', 'Home-Front War Drama', 'subgenre'),
  ('traditional-western', 'Traditional Western', 'subgenre'),
  ('revisionist-western', 'Revisionist Western', 'subgenre'),
  ('neo-western', 'Neo-Western', 'subgenre'),
  ('traditional-musical', 'Traditional Musical', 'subgenre'),
  ('music-drama', 'Music Drama', 'subgenre'),
  ('music-comedy', 'Music Comedy', 'subgenre'),
  ('investigative-documentary', 'Investigative Documentary', 'subgenre'),
  ('biography-profile-documentary', 'Biography / Profile Documentary', 'subgenre'),
  ('political-social-documentary', 'Political / Social Documentary', 'subgenre'),
  ('nature-documentary', 'Nature Documentary', 'subgenre'),
  ('music-documentary', 'Music Documentary', 'subgenre'),
  ('sports-documentary', 'Sports Documentary', 'subgenre'),
  ('true-crime-documentary', 'True Crime Documentary', 'subgenre'),
  ('sitcom', 'Sitcom', 'subgenre'),
  ('workplace-sitcom', 'Workplace Sitcom', 'subgenre'),
  ('family-sitcom', 'Family Sitcom', 'subgenre'),
  ('dramedy', 'Dramedy', 'subgenre'),
  ('procedural', 'Procedural', 'subgenre'),
  ('prestige-drama', 'Prestige Drama', 'subgenre'),
  ('soap-serial-drama', 'Soap / Serial Drama', 'subgenre'),
  ('anthology', 'Anthology', 'subgenre'),
  ('sketch-comedy', 'Sketch Comedy', 'subgenre'),
  ('reality-competition', 'Reality Competition', 'subgenre'),
  ('docuseries', 'Docuseries', 'subgenre'),
  ('late-night-talk-show', 'Late-Night Talk Show', 'subgenre'),
  ('news-satire', 'News Satire', 'subgenre'),
  ('animated-family', 'Animated Family', 'subgenre'),
  ('adult-animation', 'Adult Animation', 'subgenre'),
  ('anime-action', 'Anime Action', 'subgenre'),
  ('isekai', 'Isekai', 'subgenre'),
  ('warm', 'Warm', 'tone'),
  ('bittersweet', 'Bittersweet', 'tone'),
  ('melancholic', 'Melancholic', 'tone'),
  ('bleak', 'Bleak', 'tone'),
  ('uplifting', 'Uplifting', 'tone'),
  ('sentimental', 'Sentimental', 'tone'),
  ('playful', 'Playful', 'tone'),
  ('raunchy', 'Raunchy', 'tone'),
  ('deadpan', 'Deadpan', 'tone'),
  ('absurdist', 'Absurdist', 'tone'),
  ('satirical', 'Satirical', 'tone'),
  ('wry', 'Wry', 'tone'),
  ('tense', 'Tense', 'tone'),
  ('menacing', 'Menacing', 'tone'),
  ('unsettling', 'Unsettling', 'tone'),
  ('visceral', 'Visceral', 'tone'),
  ('cerebral', 'Cerebral', 'tone'),
  ('enigmatic', 'Enigmatic', 'tone'),
  ('meditative', 'Meditative', 'tone'),
  ('dreamlike', 'Dreamlike', 'tone'),
  ('gritty', 'Gritty', 'tone'),
  ('stylized', 'Stylized', 'tone'),
  ('earnest', 'Earnest', 'tone'),
  ('cynical', 'Cynical', 'tone'),
  ('romantic', 'Romantic', 'tone'),
  ('slow', 'Slow', 'pacing'),
  ('moderate', 'Moderate', 'pacing'),
  ('fast', 'Fast', 'pacing')
on conflict (slug) do update
set display_name = excluded.display_name,
    category = excluded.category,
    retired_at = null;
